name: timeseries-forecasting
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - dash
  - dash-bootstrap-components
  - plotly
  - polars
  - pyarrow
  - sqlalchemy
  - psycopg2
  - numpy
  - pandas
  - matplotlib
  - jupyterlab
  - jupyter
  - ipykernel
  - pip
  - pip:
    - prophet
    - functime